# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marek Šmidrkal
email: m.smidrkal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Je dobré věnovat se grafickému designu, ale lepší je toho nechat.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mareksmidrkal.cz" # the base hostname & protocol for your site
twitter_username: noaf_
github_username:  shm1ck
permalink: /:title
config:
  img:
    orig_url: /media/img/orig/

# Build settings
markdown: kramdown
